export enum StorageCalendarKey {
  SELECTED_DATA_SET,
  SELECT_DAY_MODE,
  DATA_SET,
  USER_INPUT_DATA,
  RANGE_DAYS,
  CURRENT_MONTH,
  CURRENT_MONTH_WITH_VALUES,
  YEARS,
  SELECTED_YEAR,
  SELECTED_MONTH,
  DAYS_NAMES,
  MONTH_NAMES,
}
